# Generated by Django 4.1.5 on 2023-01-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
