# Generated by Django 4.1.5 on 2023-01-14 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('crypto', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bitcoin', models.FloatField(null=True)),
                ('ethereum', models.FloatField(null=True)),
                ('tether', models.FloatField(null=True)),
                ('usdcoin', models.FloatField(null=True)),
                ('binancecoin', models.FloatField(null=True)),
                ('binanceusd', models.FloatField(null=True)),
                ('xrp', models.FloatField(null=True)),
                ('cardano', models.FloatField(null=True)),
                ('dogecoin', models.FloatField(null=True)),
                ('solana', models.FloatField(null=True)),
            ],
        ),
    ]
