# Generated by Django 4.1.5 on 2023-01-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_cryptowallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowallet',
            name='binancecoin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='binanceusd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='bitcoin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='cardano',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='dogecoin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='ethereum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='solana',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='tether',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='usdcoin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='xrp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
