# Generated by Django 4.1.5 on 2023-01-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='money',
            field=models.FloatField(null=True),
        ),
    ]
