# Generated by Django 4.1.5 on 2023-01-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0010_alter_cryptowallet_binancecoin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptowallet',
            old_name='xrp',
            new_name='ripple',
        ),
    ]
